name: Get Best Result
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: install numpy
        run: |
          pip install numpy
      - name: run python
        run: |
          python ./support/operate.py
      - name: commit
        run: |
          git add .
          git commit -m "update" -a	
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
# - name: Check out repository
#         uses: actions/checkout@v2
