name: Get Best Result
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: run python
        run: |
          python ./support/operate.py
# - name: Check out repository
#         uses: actions/checkout@v2
