name: GitHub Actions Demo
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: run python
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
