name: GitHub Actions Demo
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

# - name: Check out repository
#         uses: actions/checkout@v2
