name: Manually triggered workflow：Visual and Compare
on:
  workflow_dispatch:
    inputs:
      ModelName:
        description: 'ModelName in index.txt:'
        required: true
        default: 'Best'
      Vistype:
        description: 'Single or Compare'
        required: false
        default: 'Single'
      CompareModelName:
        description: 'CompareModelName or Baseline'
        required: false
        default: 'deeplabv3p'
jobs:
  visualresult:
    runs-on: ubuntu-latest
    steps:
      # 之前在此运行生成比较图的运行脚本即可
      - run: |
          echo "Hello ${{ github.event.inputs.ModelName }}!"
          echo "- in ${{ github.event.inputs.Vistype }}!"
