name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      num:
        description: 'test Num'
        required: true
        default: 100

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.num }}!"
